[package]
name = "ConfidentialAssetExample"
version = "1.0.0"

[dependencies]
SupraFramework = { local = "../../framework/supra-framework" }
AptosExperimental = { local = "../../framework/aptos-experimental" }

[addresses]
confidential_asset_example = "_"
