[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "_"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../framework/supra-framework" }
AptosToken = { local = "../../framework/aptos-token" }
AptosTokenObjects = { local = "../../framework/aptos-token-objects" }
=======
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }
>>>>>>> aptos-framework-v1.34.0
