[package]
name = "calculator"
version = "0.0.0"

[addresses]
account = "_"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../../framework/supra-framework" }
=======
AptosFramework = { local = "../../../framework/aptos-framework" }
>>>>>>> aptos-framework-v1.34.0
AptosStdlib = { local = "../../../framework/aptos-stdlib" }
