[package]
name = "any_example"
version = "1.0.0"

[addresses]
any_example = "0x42"
std = "0x1"

[dependencies]
MoveStdlib = { local = "../../framework/move-stdlib" }
AptosStdlib = { local = "../../framework/aptos-stdlib" }