[package]
name = "hello_prover"
version = "0.0.0"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../../framework/supra-framework" }
=======
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework/", rev = "main" }
>>>>>>> aptos-framework-v1.34.0

[addresses]


