[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
aptos_framework = "0x1"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../../framework/supra-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
=======
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token", rev = "mainnet" }
>>>>>>> aptos-framework-v1.34.0
