[package]
name = "raffle"
version = "0.0.1"

[dependencies]
SupraFramework = { local = "../../framework/supra-framework" }
AptosStdlib = { local = "../../framework/aptos-std" }


[addresses]
raffle = "_"