[package]
<<<<<<<< HEAD:tools/compute-module-expansion-size/Cargo.toml
name = "compute-module-expansion-size"
========
name = "package-generator"
description = "Move package generator for benchmarking"
>>>>>>>> aptos-framework-v1.34.0:testsuite/benchmark-workloads/package-generator/Cargo.toml
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
<<<<<<<< HEAD:tools/compute-module-expansion-size/Cargo.toml
clap = { workspace = true }
futures = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
rayon = { workspace = true }
tokio = { workspace = true }
========
aptos-framework = { workspace = true }
aptos-transaction-workloads-lib = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
move-package = { workspace = true }
>>>>>>>> aptos-framework-v1.34.0:testsuite/benchmark-workloads/package-generator/Cargo.toml
