[package]
name = "Examples"
version = "0.0.0"

[dependencies]
supra_framework = { local = "../../../framework/supra-framework" }
AptosToken = { local = "../../../framework/aptos-token" }

[addresses]
supra_framework = "0x1"
