[package]
name = "Examples"
version = "0.0.0"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../../framework/supra-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
=======
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token", rev = "mainnet" }
>>>>>>> aptos-framework-v1.34.0

[addresses]
aptos_framework = "0x1"
# replace the admin_addr with the actual admin address we created using CLI
admin_addr = "0xbeef"