[package]
name = "CliArgs"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
test_account = "_"

<<<<<<< HEAD
[dependencies.SupraFramework]
local = "../../framework/supra-framework"
=======
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
subdir = "aptos-framework"
rev = "mainnet"
>>>>>>> aptos-framework-v1.34.0
