[package]
name = 'knight'
version = '1.0.0'

[addresses]
knight = "_"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../../framework/supra-framework" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
=======
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }
>>>>>>> aptos-framework-v1.34.0
