[package]
name = "test_case"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.SupraFramework]
local = "../../../../../../aptos-move/framework/supra-framework"

[dev-dependencies]
