[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
example_addr = "_"

[dependencies]
<<<<<<< HEAD
SupraFramework = { local = "../../../framework/supra-framework" }
=======
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
>>>>>>> aptos-framework-v1.34.0
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
