[package]
name = "DataStructure"
version = "0.0.1"

[dependencies]
<<<<<<< HEAD
AptosStdlib = { local = ".../../../framework/aptos-std" }
SupraFramework = { local = ".../../../framework/supra-framework" }
=======
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-stdlib", rev = "mainnet" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

>>>>>>> aptos-framework-v1.34.0

[addresses]
std = "0x1"
